/**
 * Tailwind CSS Configuration
 * ===========================
 * Reconstructed from the production CSS bundle:
 * https://tiarphone.vercel.app/_next/static/chunks/3m1_o1abt5dat.css
 * (saved at src/styles/globals.css)
 *
 * Analysis of the compiled bundle (preflight + utilities):
 * - Tailwind version: v3.4.x
 *   (signature: `*,:before,:after,::backdrop` preflight reset,
 *   `--tw-gradient-from-position` / `--tw-contain-*` custom properties,
 *   plain CSS output without @layer / @property used by v4)
 * - Custom color scale "brand": classes bg-brand-50..900, text-brand-*,
 *   border-brand-*, ring-brand-*, from-brand-400, to-brand-900 all emit
 *   EXACTLY the Tailwind default teal palette:
 *     brand-50  #F0FDFA  brand-100 #CCFBF1  brand-200 #99F6E4
 *     brand-300 #5EEAD4  brand-400 #2DD4BF  brand-500 #14B8A6
 *     brand-600 #0D9488  brand-700 #0F766E  brand-800 #115E59
 *     brand-900 #134E4A
 *   -> brand === teal (teal was aliased to brand in the original config)
 * - Default breakpoints only: sm 640, md 768, lg 1024, xl 1280 (no custom)
 * - No `dark:` variants in the bundle -> darkMode not enabled (or unused)
 * - Default palettes also in use: gray, blue, red, green, yellow, orange,
 *   purple, pink, white, black
 * - Fonts: body font-family is
 *   system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, sans-serif
 *   (overridden sans stack); [dir=rtl] uses Segoe UI, Tahoma, Geneva, Verdana
 * - Custom animations (fade-in, fade-in-up, slide-up, slide-in-left,
 *   slide-in-right, pop-in, slide-down, float, pulse-soft) + animate-delay-*
 *   utilities were authored directly in globals.css as plain CSS classes,
 *   so they are NOT generated by this config - keep them in globals.css.
 *   They are mirrored here for convenience/parity.
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#F0FDFA',
          100: '#CCFBF1',
          200: '#99F6E4',
          300: '#5EEAD4',
          400: '#2DD4BF',
          500: '#14B8A6',
          600: '#0D9488',
          700: '#0F766E',
          800: '#115E59',
          900: '#134E4A',
        },
      },
      fontFamily: {
        sans: [
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
        rtl: ['Segoe UI', 'Tahoma', 'Geneva', 'Verdana', 'sans-serif'],
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in-left': {
          '0%': { opacity: '0', transform: 'translate(-30px)' },
          '100%': { opacity: '1', transform: 'translate(0)' },
        },
        'slide-in-right': {
          '0%': { opacity: '0', transform: 'translate(30px)' },
          '100%': { opacity: '1', transform: 'translate(0)' },
        },
        'pop-in': {
          '0%': { opacity: '0', transform: 'scale(.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'slide-down': {
          '0%': { opacity: '0', transform: 'scaleY(0)', 'transform-origin': 'top' },
          '100%': { opacity: '1', transform: 'scaleY(1)', 'transform-origin': 'top' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '.7' },
        },
      },
      animation: {
        'fade-in': 'fade-in .4s ease-out',
        'fade-in-up': 'fade-in-up .5s ease-out forwards',
        'slide-up': 'slide-up .5s ease-out forwards',
        'slide-in-left': 'slide-in-left .5s ease-out forwards',
        'slide-in-right': 'slide-in-right .5s ease-out forwards',
        'pop-in': 'pop-in .4s ease-out forwards',
        'slide-down': 'slide-down .25s ease-out forwards',
        float: 'float 3s ease-in-out infinite',
        'pulse-soft': 'pulse-soft 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
